### ISSUE TITLE
[BUG] Can't play audio and video in encrypted rooms

### ISSUE THREAD

**Issue by T-bond** [gary-kim/riotchat#110]
If I send a video/audio or if I receive one I can not play it, nor can download it.

Always getting the following popup when the message containing the attachment gets loaded (navigation to the room, where it was sent, or going back in history):
![image](https://user-images.githubusercontent.com/3778556/89325253-d2473600-d688-11ea-8823-b6aa51d7af1e.png)

Also the player is different:
![image](https://user-images.githubusercontent.com/3778556/89325437-133f4a80-d689-11ea-8d26-a621b6a483a7.png)
It can't load the length, and also there is no link to download it.

Also checked on app.element.io and it is working correctly:
![image](https://user-images.githubusercontent.com/3778556/89325362-f7d43f80-d688-11ea-939c-15c88d9119a1.png)

I checked that Firefox says that:
`Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://samedomainasriotchat/randomhashhere (“media-src”).`
(The media is playable from that URI if I open it in another tab)

I also tried to allow it in the plugin by adding:
```PHP
$csp->addAllowedMediaDomain($this->request->getServerHost());
$csp->addAllowedMediaDomain($default_server_domain);
$csp->addAllowedMediaDomain('blob:');
```
to custom_apps/riotchat/lib/Controller/ConfigController.php::index()

It gets applied correctly, as it appears in the browser's request:
![image](https://user-images.githubusercontent.com/3778556/89326118-1b4bba00-d68a-11ea-903b-c7f26e9e15a1.png)

Somebody from the community helped to check it out, and we got to the result that it only breaks in encrypted rooms.
But when it goes wrong it is wrong on their end too.
In the Vector hosted Element it works, that's why I guess it will be a plugin issue.

Installed Riotchat version: 0.6.2
Nextcloud: 19.0.0
Using it with Nginx reverse proxy (no CSP settings on that side)
Firefox: 78.0.2 on Arch Linux

Please tell me if you need any more info.

**Comment by gary-kim** [comment]
Thank you, that's a very detailed bug report! I'll take a look as soon as I have some time or someone else can if they'd like.

**Comment by T-bond** [comment]
We figured out that, if you add `'blob:'` to media-src in `lib/public/AppFramework/Http/ContentSecurityPolicy.php` then, the media gets playable. (The annoying popup still remains, and the download link still does not appear)
I hope this information helps a little bit more.
