### ISSUE TITLE
Undefined index: features at /apps2/riotchat/lib/AppInfo/Application.php#51

### ISSUE THREAD

**Issue by c0ryb4k3r** [gary-kim/riotchat#139]
ElementWeb removed the feature tag in develop.config.json so the app was not loading properly. Manually adding an empty features section works as a band-aid:

vector-im/element-web@2a25c6a

**Comment by gary-kim** [comment]
It looks like for the most part, the features part of the config doesn't do anything anymore so we can probably just get rid of that part of the config.

**Comment by gary-kim** [comment]
Thank you @c0ryb4k3r for reporting this!
