### ISSUE TITLE
Can't open files on encrypted channel

### ISSUE THREAD

**Issue by florianfidh** [gary-kim/riotchat#154]
Hello,

I can't open files once they are unencrypted in the chat when it's on an encrypted channel. The file disappears when you click on it.
It's working fine when it's not encrypted though.

Nextcloud is 18.0.5.

Thanks,
Florian

**Comment by gary-kim** [comment]
#115 tried to fix this issue for the most part but there is still an issue where it seems that loading `usercontent.js` sometimes results in 401s. 

https://matrix.to/#/!CDWVdagHmbnQcqIPyv:garykim.dev/$AU3WDYQATMh_ZMOu4MjJzGE-xFV2broKTpitfbrt4hk?via=garykim.dev&via=matrix.org&via=mwcloud.microway.com%3A8448

Let's keep this open to try to fully fix this issue.
