### ISSUE TITLE
Fix Dev Link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by gary-kim** [gary-kim/riotchat#163]
So, it looks like the link to setting up the dev environment in the [CONTRIBUTING.md](https://github.com/gary-kim/riotchat/blob/master/CONTRIBUTING.md) is broken. Should just need to change it to point at <https://docs.nextcloud.com/server/19/developer_manual/general/devenv.html> to fix it.

**Comment by NauhcNoohc** [comment]
Alright, i will take it up. Please assign it to me. Thanks

**Comment by gary-kim** [comment]
Closed by #164
