### ISSUE TITLE
Media not showing up

### ISSUE THREAD

**Issue by scanno** [gary-kim/riotchat#19]
Hi,
Great initiative. Running matrix-synapse for a while already on my own server and thought to try your Nextcloud integration. Seems to work however no media is retrieved from the matrix server. The retrieval of the media (pictures, icons, avatars) does work with the riot web client, riotx and all other clients.

**Comment by gary-kim** [comment]
Yep, I can reproduce the issue. Thank you very much for the bug report. Fix is incoming.

**Comment by gary-kim** [comment]
`v0.1.5` has been released with a fix for this issue.

**Comment by scanno** [comment]
Looking good, however when there are videos, only a thumbnail is shown and the videos cannot be played.
