### ISSUE TITLE
Integration Manager & Jitsi cannot be reached

### ISSUE THREAD

**Issue by scanno** [gary-kim/riotchat#23]
Hi,
Found two more reachability problems:

When trying to access a jitsi videoconference, i get the message: `Requests to the server have been blocked by an extension.` (ofc other clients work)

Also when trying to open the integration manager i get the message:
```
Cannot connect to integration manager
The integration manager is offline or it cannot reach your homeserver.
```
The integration manager works on other clients for the same homeserver.

**Comment by gary-kim** [comment]
That would be a result of the CSP being used. Let's revert to the CSP allowing all connections for now for Riot and we can more slowly enable it again while checking that nothing breaks.

**Comment by gary-kim** [comment]
@scanno Any chance you can try #24 to see if that fixes your issue? It seems to fix it in my testing but just want to be sure.

**Comment by scanno** [comment]
@gary-kim Would love to test, but no means right now to build.

**Comment by gary-kim** [comment]
That's fine. `v0.1.6` should have a fix for your issue.

**Comment by scanno** [comment]
@gary-kim v0.1.6 seems to work fine. Can add widgets, movies are playing and jitsi starts.

Only one problem with jitsi, it cannot get microphone and video permissions from the browser. Guess Nextcloud blocks that.

**Comment by gary-kim** [comment]
> Only one problem with jitsi, it cannot get microphone and video permissions from the browser. Guess Nextcloud blocks that.

That's strange, it seems to work on my instance. Are you accessing through `https`? I seem to recall you cannot request camera permissions when accessing though `http`.

**Comment by scanno** [comment]
> > Only one problem with jitsi, it cannot get microphone and video permissions from the browser. Guess Nextcloud blocks that.
> 
> That's strange, it seems to work on my instance. Are you accessing through `https`? I seem to recall you cannot request camera permissions when accessing though `http`.

Seems to be a Chrome on Linux problem. Firefox asks for the permissions

**Comment by EchedeyLR** [comment]
This seems to be a problem again.

It seems that the error is on the own request to the server.

**Comment by EchedeyLR** [comment]
![2022-01-24_11-07](https://user-images.githubusercontent.com/56733813/150771965-158929b9-96d4-42bf-9ec0-b3a9d6680fa0.png)

**Comment by gary-kim** [comment]
That looks like an error on the integration manager. Any chance you could try with Scalar as well?

**Comment by EchedeyLR** [comment]
That is the case, Scalar works well which is the default. The only one which doesn't work is that.

I can try again. Maybe was just a temporary issue.

**Comment by EchedeyLR** [comment]
I tried and still cannot.

Main difference is that my server is behind a reverse proxy server. Maybe Matrix client is not connecting well because is not prepared to use specific headers to get information to know where is running?

**Comment by EchedeyLR** [comment]
It seems that my issue was because I didn't configure the trusted proxies correctly.
