### ISSUE TITLE
Nothing appears (Yunohost)

### ISSUE THREAD

**Issue by Thovi98** [gary-kim/riotchat#26]
Hello ! 

What an amazing idea to create this app !
Unfortunately, it doesn't work yet on my server :( 
Installations works without problem, but when I go to the app, nothing appaers : 
![Sélection_001](https://user-images.githubusercontent.com/51749973/81169804-c53b7d80-8f99-11ea-8f50-ec8b0bc6d715.png)
I don't know how I can help you to provide more informations, but here is what I can give you : 
I run Nextcloud 18.02 on Yunohost 3.7.1.3

Thanks for your work, I hope to use it soon :D

**Comment by gary-kim** [comment]
That is certainly an issue. Thank you for your report.
Any chance you could paste your browser console log when loading the page?

**Comment by Thovi98** [comment]
For sure ! 
Is it this that you ask ?

![Sélection_001](https://user-images.githubusercontent.com/51749973/81173487-6d544500-8fa0-11ea-9f05-ef2f31ae5399.png)

**Comment by gary-kim** [comment]
Yes, thank you.
That's strange. It looks like the iframe url is loaded properly but then riot itself is not loading properly. Do you have an ad blocker by any chance?

**Comment by Thovi98** [comment]
No, I deactivate Ublock Origin and Ghostery on my server domain.
It's the only app of my Nextcloud where something like this appaers ! 

Don't hesitate to ask me to check some things, I'm not a developper but if you explain me, I can try :)

**Comment by Thovi98** [comment]
And for your information, I tried also on Chromium, without any ad blocker or extension, and I've same issue.

**Comment by gary-kim** [comment]
Seems to be a Yunohost specific issue. I'll try to find an extra computer I can set up with Yunohost to test this.
Actually, is there a way to test Yunohost without installing it on a system? I'll try to find a way.

**Comment by Thovi98** [comment]
There is well a demo version of Yunohost where you can try Nextcloud on Yunohost. 
I just tried Riot Chat on it, but same issue, so it's effectively maybe Yunohost related. 
https://demo.yunohost.org/

But you cannot access ssh of this demo to better investigate unfortunately. 
Or there is the possibility to install it on a VM. You can see all here : https://yunohost.org/#/install

Thanks for your time :D

**Comment by gary-kim** [comment]
So, the issue seems to be that when loading Riot, the requests for the static resources are being redirected to the login page by Yunohost. I don't know why that is but it seems like it's happening to quite a few of the requests. I think this would be an upstream issue in Yunohost. Gonna try debugging a little further.

**Comment by Thovi98** [comment]
Wow you are fast ! I don't get all of what you say, but it's nice that you already can say what is the problem ! Thanks :D

**Comment by TheNomad11** [comment]
In my case it says it cannot reach homeserver - also an Yunohost (security?) issue, I suppose. Might not be reachable from outside Yunohost?

**Comment by gary-kim** [comment]
> In my case it says it cannot reach homeserver - also an Yunohost (security?) issue, I suppose. Might not be reachable from outside Yunohost?

That sounds like a separate issue. Could you check that you're on the latest version (there was an update recently to fix CSP issues) then make a new issue for it? Thank you.

**Comment by TheNomad11** [comment]
Same with newest update. I suppose it is because my Synapse server is set to not public. But if I set it to be public, the whole world will be able to use the server it seems, but not sure. There is not enough documentation on Yunohost about that. I'm going to go further with that, not the most important thing

**Comment by Thatoo** [comment]
I face the exact same problem

**Comment by Thatoo** [comment]
It seems like the solution is explained in here : https://github.com/YunoHost-Apps/nextcloud_ynh/pull/332

**Comment by gary-kim** [comment]
Thank you for reporting this upstream @Thatoo

**Comment by sebmennetrier** [comment]
Another simple solution is now available : https://github.com/YunoHost-Apps/nextcloud_ynh/pull/340

**Comment by Thovi98** [comment]
Since Nextcloud 20.04 is stable for Yunohost, this issue is fixed.
Thanks @gary-kim for your support and amazing work !!
