### ISSUE TITLE
Option to jump directly to /riotchat/#/login

### ISSUE THREAD

**Issue by bpcurse** [gary-kim/riotchat#29]
First of all, thank you very much for your work integrating Riot in Nextcloud. I didn't think this would happen so fast :partying_face: :+1: 

The app opens at /riotchat/#/welcome where you can select the language and choose between register or login.
In a setup with a local homeserver where all users are already registered or self registering isn't possible it would be nice to have a setting that skips the welcome screen and jumps directly to the login screen.

**Comment by gary-kim** [comment]
I like the idea although having an option for this is probably a bit overkill. Since the login page also has the sign up page, what do you think of making it so that login is the default page if a custom homeserver has been set?

**Comment by bpcurse** [comment]
Thank you for taking this into consideration.
Regarding our use case this would be an appropriate solution. And I think it is also ok if you want it to be still possible to register on a self-hosted homeserver, as the option is available on the login page, too.
IMO it is a good solution, although I wouldn't say a simple checkbox is overkill, as there are other things like the experimental features most users won't need, that could be put into a config file, instead of the settings :wink: 

![Screenshot_2020-05-08 Cloud - Riot Chat](https://user-images.githubusercontent.com/29312856/81396008-eb415900-9124-11ea-9c9f-24bbf56e3aca.png)
