### ISSUE TITLE
CORS issue when account domain and homeserver domain are different

### ISSUE THREAD

**Issue by Galbar** [gary-kim/riotchat#308]
When doing p2p videocalls the element client tries to query https://example.com/.well-known/matrix/client which gets blocked by the CORS policy.

I have my synapse server at https://matrix.example.com and the homeserver domain is example.com . I have the endpoint https://example.com/.well-known/matrix/client that returns:
```json
{
  "m.homeserver": {
    "base_url": "https://matrix.example.com"
  }
}
```

**Comment by gary-kim** [comment]
I believe this is a configuration error. The server you're hosting the `.well-known/matrix/client` from should be returning CORS headers for that response that allows the request.

https://matrix.org/docs/spec/client_server/r0.6.1#well-known-uri

**Comment by Galbar** [comment]
Thanks! I always get confused with CORS :sweat_smile:
