### ISSUE TITLE
Include Changelog into App Store listing

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [gary-kim/riotchat#376]
It would be tremendously helpful to have the changelog included into the Nextcloud App Store listing. Currently, any (potentially breaking) changes must be fetched from this repository. Especially for production systems, a changelog at a glace in the app store listing might be helpful.

**Comment by gary-kim** [comment]
Yup, I'm trying to get that working at the moment. It seems to be due to the `v` prefix in the changelog so I have a PR going trying to make the changelog parser work with `v` prefix as well: https://github.com/nextcloud/appstore/pull/852

**Comment by gary-kim** [comment]
This is working these days so I'm going to close this.
