### ISSUE TITLE
internal server error after upgrade Element riotchat app on nextcloud 19.0.13

### ISSUE THREAD

**Issue by ressit** [gary-kim/riotchat#386]
nextcloud 19.0.13
apache2 frontend
php7.3
Element riotchat app installed but not used

After applying the offered upgrade of the Element riotchat the nextcloud server was no more responding, internal server error.
Even a trial to uninstall the app with occ commands from command line was not successful because of php errors thrown.

After removal of the apps/riotchat folder, the nexctcloud server became usable again.

The logfile shows an error on access to IBootstrap which is assumed to be available on nextcloud 20 first:

```
[Sat Jul 31 18:13:09.413792 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP Fatal error:  Interface 'OCP\\AppFramework\\Bootstrap\\IBootstrap' not found in /var/www/nextcloud/apps/riotchat/lib/AppInfo/Application.php on line 35
[Sat Jul 31 18:13:09.414224 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP Stack trace:
[Sat Jul 31 18:13:09.414241 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP   1. {main}() /var/www/nextcloud/ocs/v2.php:0
[Sat Jul 31 18:13:09.414248 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP   2. require_once() /var/www/nextcloud/ocs/v2.php:24
[Sat Jul 31 18:13:09.414254 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP   3. OC_App::loadApps() /var/www/nextcloud/ocs/v1.php:56
[Sat Jul 31 18:13:09.414260 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP   4. OC_App::loadApp() /var/www/nextcloud/lib/private/legacy/OC_App.php:128
[Sat Jul 31 18:13:09.414266 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP   5. OC_App::requireAppFile() /var/www/nextcloud/lib/private/legacy/OC_App.php:155
[Sat Jul 31 18:13:09.414271 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP   6. require_once() /var/www/nextcloud/lib/private/legacy/OC_App.php:266
[Sat Jul 31 18:13:09.414277 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP   7. OC\\URLGenerator->linkToRoute() /var/www/nextcloud/apps/theming/appinfo/app.php:38
[Sat Jul 31 18:13:09.414283 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP   8. OC\\Route\\CachingRouter->generate() /var/www/nextcloud/lib/private/URLGenerator.php:83
[Sat Jul 31 18:13:09.414289 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP   9. OC\\Route\\CachingRouter->generate() /var/www/nextcloud/lib/private/Route/CachingRouter.php:60
[Sat Jul 31 18:13:09.414295 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP  10. OC\\Route\\CachingRouter->loadRoutes() /var/www/nextcloud/lib/private/Route/Router.php:331
[Sat Jul 31 18:13:09.414301 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP  11. OC\\Route\\CachingRouter->requireRouteFile() /var/www/nextcloud/lib/private/Route/Router.php:151
[Sat Jul 31 18:13:09.414306 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP  12. OC\\Route\\CachingRouter->setupRoutes() /var/www/nextcloud/lib/private/Route/Router.php:380
[Sat Jul 31 18:13:09.414312 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP  13. class_exists() /var/www/nextcloud/lib/private/Route/Router.php:401
[Sat Jul 31 18:13:09.414317 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP  14. spl_autoload_call() /var/www/nextcloud/lib/private/Route/Router.php:401
[Sat Jul 31 18:13:09.414323 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP  15. Composer\\Autoload\\ClassLoader->loadClass() /var/www/nextcloud/lib/private/Route/Router.php:401
[Sat Jul 31 18:13:09.414328 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP  16. Composer\\Autoload\\includeFile() /var/www/nextcloud/lib/composer/composer/ClassLoader.php:322
[Sat Jul 31 18:13:09.414334 2021] [php7:notice] [pid 57608] [client 9.11.9.11:31338] PHP  17. include() /var/www/nextcloud/lib/composer/composer/ClassLoader.php:444
[Sat Jul 31 18:13:10.986447 2021] [php7:notice] [pid 58310] [client 9.11.9.11:31425] PHP Fatal error:  Interface 'OCP\\AppFramework\\Bootstrap\\IBootstrap' not found in /var/www/nextcloud/apps/riotchat/lib/AppInfo/Application.php on line 35

```
After an upgrade of nextcloud to release 20, the Element riotchat app shows version 0.8.1

**Comment by gary-kim** [comment]
That's a big problem. Let me get that fixed very quick

**Comment by fnetX** [comment]
I assume the recent release just addresses this issue?

Main problem for me now: Simply updating the app (changelog not displayed inside NC app), leads to very weird behaviour on newer installations and disabled the app after "updating" nextcloud ...

What's the supposed way to prevent people of newer installations to updating to this version? Any way to do this, on top of the mention in the Changelog?

**Comment by nursoda** [comment]
The reason is that Nextcloud seems to install the newest version upon App-Updates, no matter whether the latest version was released for an older NC version only as in this case: 0.8.2 is marked compatible with NC19 only. 0.8.1 is marked compatible for NC 19-22. In my opinion, this is a SERVER issue, as the mechanism should prohibit such an update. In my case, I used this command:

`occ app:update --all`

This lead to 0.8.2 being installed on my NC22.1RC1 test instance, leading to the request to do an `upgrade` which itself lead to an error `Updates between multiple major versions are unsupported`.

**Comment by gary-kim** [comment]
Well, I'm about to release `v0.9.0` which should fix that issue anyways but yes, that does seem problematic.

**Comment by ressit** [comment]
The app update to 0.9.0 was installable a nc 20.0.11, thanks for the quick solution. The issue could be closed.

**Comment by ressit** [comment]
The app update of the disabled riotchat app to 0.9.1 made the nexcloud browser tab hang, "something is slowing down" browser message. The issue could be solved from command line:
sudo -u www-data php occ  app:remove riotchat

**Comment by gary-kim** [comment]
@ressit Do you have logs for that? That sounds like a serious issue.

I'm also using v0.9.1 on my own instance but don't have the same issue.

**Comment by ressit** [comment]
No, I did not see anything related in the logs.
