### ISSUE TITLE
The requested uri() cannot be processed by cron

### ISSUE THREAD

**Issue by DatAres37** [gary-kim/riotchat#393]
I'm having these errors logs every 5 minutes since upgrading to Nextcloud 22.1.0 today. The app itself works fine as long as I can tell. Not sure if it's a Nextcloud or riotchat issue, I'd just assume the latter. 

`[no app in context] Fatal: Could not boot riotchat: The requested uri() cannot be processed by the script '/var/www/html/cron.php')`

`
{"reqId":"iM6ZP0ATTKWIlsezg5UL","level":4,"time":"2021-08-06T19:45:01+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Could not boot riotchat: The requested uri() cannot be processed by the script '/var/www/html/cron.php')","userAgent":"--","version":"22.1.0.1","exception":{"Exception":"Exception","Message":"The requested uri() cannot be processed by the script '/var/www/html/cron.php')","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Http/Request.php","line":796,"function":"getRawPathInfo","class":"OC\\AppFramework\\Http\\Request","type":"->","args":[]},{"file":"/var/www/html/custom_apps/riotchat/lib/AppInfo/Application.php","line":66,"function":"getPathInfo","class":"OC\\AppFramework\\Http\\Request","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":178,"function":"boot","class":"OCA\\RiotChat\\AppInfo\\Application","type":"->","args":[{"__class__":"OC\\AppFramework\\Bootstrap\\BootContext"}]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":205,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":["riotchat"]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":139,"function":"loadApp","class":"OC_App","type":"::","args":["riotchat"]},{"file":"/var/www/html/cron.php","line":54,"function":"loadApps","class":"OC_App","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Request.php","Line":770,"CustomMessage":"Could not boot riotchat: The requested uri() cannot be processed by the script '/var/www/html/cron.php')"},"id":"610d913ddfcfd"}`

**Comment by gary-kim** [comment]
Ah yes, that is a issue in this app. Fix incoming
