### ISSUE TITLE
Automated language setting not working yet

### ISSUE THREAD

**Issue by bpcurse** [gary-kim/riotchat#40]
There is already a todo note in ConfigController.php:72, but it is probably good to have it open as a separate issue to have an overview?

**Comment by gary-kim** [comment]
I just looked into this further and it seems the reason the current implementation doesn't work is because Nextcloud specifically only sets `IL10N` to a language if the app supports that language (this actually makes a lot of sense).

**Comment by bpcurse** [comment]
It seems to be working now :+1:  At least for the german language setting.
This issue could be closed as far as I am concerned. Thank you :)

**Comment by gary-kim** [comment]
Closing as resolved
