### ISSUE TITLE
Nextcloud 24 support

### ISSUE THREAD

**Issue by spaetz** [gary-kim/riotchat#467]
I love to use Element from within my Nextcloud! However, I'd like to upgrade to Nextcloud 24 now, which is offered through the stable release channel, but Nextcloud-riotchat does not announce compatability with NC24 yet. How difficult would it be to support it?

**Comment by gary-kim** [comment]
I think the `@nextcloud/vue` package needs to be updated which is causing some issues currently. I'll try to get around to fixing that as soon as I can. It is the middle of finals week at school so I don't think I can get around to it this week.

If someone else wants to do that, they are also perfectly welcome to.

**Comment by spaetz** [comment]
Thanks for the info, and no hurry at all. Good luck with the finals.
