### ISSUE TITLE
Mic and Camera acces during call is suppressed

### ISSUE THREAD

**Issue by compgeniuses** [gary-kim/riotchat#47]
I noticed that whenever a call is made from within the App. 
The mic and or camera for laptop is suppresed, and thereby the party can not see or hear you.
Kindly check on this issue.

**Comment by gary-kim** [comment]
That's strange. I've tested it on Firefox and it works fine. Could I ask what version of the app your on?

In the meantime, I'll also check Chromium to see if it behaves differently

**Comment by gary-kim** [comment]
Okay, found the issue, fix incoming
