### ISSUE TITLE
l10n: Change the HTML abbreviation

### ISSUE THREAD

**Issue by Valdnet** [gary-kim/riotchat#473]
In the following text string, proposes to change the HTML abbreviation "iframe" to "inline frame".

https://github.com/gary-kim/riotchat/blob/e98717b14badc88f40293d4f593e4618808dbb7d/src/components/AdminSettings.vue#L91

**Comment by gary-kim** [comment]
I'm worried that might make it difficult for people to search up what they need to do in order to allow their SSO system to be iframed. Do we use the "inline frame" somewhere else in Nextcloud as well?

Always very thankful for all you do @Valdnet!

**Comment by Valdnet** [comment]
> Do we use the "inline frame" somewhere else in Nextcloud as well?

It is not present in other text strings for Nextcloud instances.

> I'm worried that might make it difficult for people to search up what they need to do in order to allow their SSO system to be iframed.

The information is for the instance administrator who may actually be easier to understand. We can leave it that way 😉.

Is this text string also for the administrator?

`This iframe is not supported in your browser.`

**Comment by gary-kim** [comment]
> Is this text string also for the administrator?
> 
> `This iframe is not supported in your browser.`

Is that a string from this app? I don't seem to be able to find it.

It sounds like something for a user rather than an administrator, though.

**Comment by Valdnet** [comment]
> Is that a string from this app?

Sorry, it's actually from another app 😉. I had a wrong look at the source of the text string. So it turns out that "iframe" is also used in another app.

I think you can close this issue.
