### ISSUE TITLE
"Internal server error" 

### ISSUE THREAD

**Issue by hsuutari** [gary-kim/riotchat#540]
With an update of Element I'm getting "internal server error" on the Element web app. Nextcloud itself and other apps work.

Nextcloud 25.0.12
Element for Nextcloud 0.16.1
Debian Bullseye with PHP 7.4

"Internal Server Error
The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log."

Here's some log from /usr/local/share/nextcloud/data/nextcloud.log:

{"reqId":"H0lH1PZMoVdpzYEiIp2a","level":3,"time":"2023-10-05T16:42:51+00:00","remoteAddr":"192.168.1.168","user":"0015e5be-a1bf-1030
-9e97-d79560756b5e","app":"index","method":"GET","url":"/cloud/index.php/apps/riotchat/riot/sw.js","message":"syntax error, unexpect
ed ')', expecting '|' or variable (T_VARIABLE) in file '/usr/local/share/nextcloud/apps/riotchat/lib/FileResponse.php' line 45","use
rAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0","version":"25.0.12.0","exception":{"Exception":"Exc
eption","Message":"syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE) in file '/usr/local/share/nextcloud/apps/rio
tchat/lib/FileResponse.php' line 45","Code":0,"Trace":[{"file":"/usr/local/share/nextcloud/lib/private/AppFramework/App.php","line":
172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/share/nextcloud/lib/private/
Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/local/share/nextcloud/lib/
base.php","line":1053,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/local/share/nextcloud/index.php","li
ne":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/local/share/nextcloud/lib/private/AppFramework/Http/Dispat
cher.php","Line":165,"Previous":{"Exception":"ParseError","Message":"syntax error, unexpected ')', expecting '|' or variable (T_VARI
ABLE)","Code":0,"Trace":[{"file":"/usr/local/share/nextcloud/lib/composer/composer/ClassLoader.php","line":428,"function":"Composer\
\Autoload\\includeFile"},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"file":"/usr/local/share/ne
xtcloud/apps/riotchat/lib/Controller/StaticController.php","line":158,"function":"spl_autoload_call"},{"file":"/usr/local/share/next
cloud/apps/riotchat/lib/Controller/StaticController.php","line":136,"function":"createFileResponseWithContent","class":"OCA\\RiotCha
t\\Controller\\StaticController","type":"->"},{"file":"/usr/local/share/nextcloud/apps/riotchat/lib/Controller/StaticController.php"
,"line":103,"function":"createFileResponse","class":"OCA\\RiotChat\\Controller\\StaticController","type":"->"},{"file":"/usr/local/s
hare/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"riot","class":"OCA\\RiotChat\\Controller\\Static
Controller","type":"->"},{"file":"/usr/local/share/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"ex
ecuteController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/share/nextcloud/lib/private/AppFramew
ork/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/share/ne
xtcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/local/
share/nextcloud/lib/base.php","line":1053,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/local/share/next
cloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/local/share/nextcloud/apps/riotchat/li
b/FileResponse.php","Line":45},"CustomMessage":"--"}}

**Comment by robertoszek** [comment]
Have you already tried what is suggested on #537 ?
Seems like the same error message to me.

**Comment by hsuutari** [comment]
The [#537](https://github.com/gary-kim/riotchat/issues/537) fixes this issue, thank you.
Sorry about the duplicate.
