### ISSUE TITLE
OIDC not allowed to load /_synapse/client/oidc/callback as iframe

### ISSUE THREAD

**Issue by verymilan** [gary-kim/riotchat#591]
Hi there, i have seen that https://github.com/gary-kim/riotchat/pull/80 exists and am wondering if i am getting this wrong... `/_synapse/client/oidc/callback` sets `X-Frame-Options: DENY` and `frame-ancestors 'none';`. I have tried to modify these for the Matrix proxy without success (I was only able to add to these which messes with the syntax at least for ancestors, or to have duplicates).

Is it really something that could be controlled like with the references pullrequest? Or is it perhaps possible to go through the SSO routine using a different tab vs the iframe?

**Comment by gary-kim** [comment]
Could you provide more information about how you get to the login page
and your configuration? I am unable to reproduce this right now, the
automatic redirect is opening the page in a new tab when attempting to
login with SSO.

**Comment by verymilan** [comment]
Oh no, I am so sorry, this is not a deployment done by me and it turns out they are using the "External sites" plugin instead. I wasn't expecting this so I didn't check. So sorry for the noise!
