### ISSUE TITLE
Can't connect since Nextcloud 30.0.2

### ISSUE THREAD

**Issue by koanya** [gary-kim/riotchat#665]
Since I upgraded Nextcloud from version 29 to 30, I can't connect to any matrix server with Riotchat. I tried to connect on my selfhosted  matrix server and on matrix.org server and I have the same behaviour : when I click to connect, it tried to connect and display "authentification..." indefinitely :
![image](https://github.com/user-attachments/assets/8c3f9eec-a33d-49a8-b6e2-37c105ff5876)

I can log in on my selfhosted matrix server with any other application successfully. I have no error message in matrix logs or in nextcloud logs when I tried to connect with Riotchat. 

Nextcloud version : 30.0.2
Riotchat version : 0.18.4

**Comment by koanya** [comment]
Some more information for this bug.

I saw more bugs in Nextcloud or this repository on this subject ([here](https://github.com/nextcloud/docker/issues/2349) and [here](https://github.com/gary-kim/riotchat/issues/671)). Like this 2 bugs, my problem come from CSP.
In the browser console, I have the error "Content-Security-Policy : Refused to create a worker from https://nextcloud.example.fr/index.php/apps/riotchat/riot/bundles/a8d349d8386f5f1d7cd7/indexeddb.worker.js because it violates the following Content Security Policy directive: : « worker-src blob: »" when I try to log in with riotchat.
Here my current CSP obtain with the command "curl -I https://domain.tld/apps/riochat/ -u USERNAME:PASSWORD and I have mand curl -I https://domain.tld/apps/riochat/ -u USERNAME:PASSWORD" :

```
HTTP/1.1 404 Not Found
Date: Fri, 13 Dec 2024 11:15:26 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: noindex, nofollow
X-XSS-Protection: 1; mode=block
Set-Cookie: ocl5n7hw78et=gf3us5polio86c3kfbdsdnt2e7; path=/; secure; HttpOnly; SameSite=Lax
Set-Cookie: oc_sessionPassphrase=lkBu5%2BCKtw7lanB8KoRyHHQIBXuqBv4PtbQoVO%2FwnQPzGNl%2B0Q0nHFlGW06vLdX7fGLaJ%2B9KcmYh%2BLjnk1IA0ERMAc%2B9ii2r1e7TsE3GaOvI44yHDOew%2Bqw6%2F0Qd5WL3; path=/; secure; HttpOnly; SameSite=Lax
Set-Cookie: ocl5n7hw78et=gf3us5polio86c3kfbdsdnt2e7; path=/; secure; HttpOnly; SameSite=Lax
Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self';script-src 'nonce-TMnNTNB/GDtoVodhEhc5fgLx4A0f3txvooO5EDRi8Wk=';script-src-elem 'strict-dynamic' 'nonce-TMnNTNB/GDtoVodhEhc5fgLx4A0f3txvooO5EDRi8Wk=';style-src 'self' 'unsafe-inline';img-src 'self' data: blob: https://*.tile.openstreetmap.org https://office.example.fr;font-src 'self' data:;connect-src 'self';media-src 'self';frame-src 'self' nc: https://office.example.fr;frame-ancestors 'self' https://office.example.fr;worker-src blob:;form-action 'self' https://office.example.fr
Set-Cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
Set-Cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
Set-Cookie: ocl5n7hw78et=gf3us5polio86c3kfbdsdnt2e7; path=/; secure; HttpOnly; SameSite=Lax
Set-Cookie: ocl5n7hw78et=gf3us5polio86c3kfbdsdnt2e7; path=/; secure; HttpOnly; SameSite=Lax
Set-Cookie: ocl5n7hw78et=gf3us5polio86c3kfbdsdnt2e7; path=/; secure; HttpOnly; SameSite=Lax
X-Request-Id: Uloi6KguJAKSQg2E4a1r
Cache-Control: no-cache, no-store, must-revalidate
Feature-Policy: autoplay 'self';camera 'none';fullscreen 'self' https://office.example.fr;geolocation 'self';microphone 'none';payment 'none'
Content-Length: 5378
Content-Type: text/html; charset=UTF-8
```
Do you think the problem come from Nextcloud or from Riotchat (or from my settings) ?

**Comment by koanya** [comment]
I resolved my problem by adding " $csp->addAllowedWorkerSrcDomain($this->request->getServerHost());" at the line 184 to add the  "worker-src 'self'" policy. It is a good or a dirty fix ?

**Comment by gary-kim** [comment]
Dupe of #671 

> I resolved my problem by adding " $csp->addAllowedWorkerSrcDomain($this->request-> getServerHost());" at the line 184 to add the "worker-src 'self'" policy. It is a good or a dirty fix ?

I had a suspicion that was the issue which I was hoping to confirm from the headers in #671. That is the fix I would do. Would you mind making that a PR?

**Comment by koanya** [comment]
I will make the PR
