### ISSUE TITLE
Riot NC does not work with Firefox ESR.

### ISSUE THREAD

**Issue by microniko** [gary-kim/riotchat#67]
I would like to test Riot NC client but « Impossible de joindre le serveur d’accueil Vérifiez que vous avec une connexion internet stable ou contactez l’administrateur du serveur » (sorry, it is in French).
In the Firefox console : 
```
Error processing homeserver config: {…} 
base_url: "https://matrix-client.matrix.org"
​error: "Homeserver URL does not appear to be a valid Matrix homeserver"
state: "FAIL_ERROR" 
```

I also tested https://matrix.fdn.fr witch also doesn't work.

**Client** : 
- Firefox [68.9.0esr] ;
-  Debian Buster.

(*Works with Chromium*)

**Server** :
- OS : Debian Buster ;
- Apache ;
- PostgreSQL 11.7
- PHP : 	7.3.14
- NextCloud : 18.0.6 ;
- Riot Chat : 0.4.3.

**Comment by gary-kim** [comment]
I suspect that this is due to some differences in how `Content-Security-Policy` is handled in older versions of Firefox. We can investigate this a bit.

**Comment by bentolor** [comment]
Nota bene: I saw the same error in current Firefox 85 caused by a request block to `https://matrix-client.matrix.org/_matrix/client/versions` by uMatrix. Allowing the request fixed the issue.

**Comment by microniko** [comment]
@bentolor : You're right, uMatix blocked requests from Matrix server :\
