### ISSUE TITLE
Riotchat/element not working with nextcloud-30 because of wrong Content Security Policy

### ISSUE THREAD

**Issue by nowatbuer** [gary-kim/riotchat#671]
After switching my docker installaltion from  nextcloud-29 to nextcloud-30 chrome  in nextcloud shows:  
Dein Element ist falsch konfiguriert
Failed to construct 'Worker': Access to the script at 'https://cloud.xx.de/apps/riotchat/riot/bundles/1c4a7dc1375053e9cf63/playback.worker.js' is denied by the document's Content Security Policy. 
I could make it work as described here: https://github.com/nextcloud/docker/issues/2349#issuecomment-2536423460 . Someone mentioned, that is it the wrong place to correct that behaviour. Unfortunately I have no idea what to change else.

**Comment by gary-kim** [comment]
Your issue may be that you have your host set incorrectly. Could you provide the `Content-Security-Policy` that you see from running the following (make sure to remove any sensitive information.

```
curl -I https://domain.tld/apps/riochat/riot/ -u USERNAME:PASSWORD
```

> The command is the same one that was requested from https://github.com/nextcloud/docker/issues/2349

The `Content-Security-Policy` should include something like `frame-ancestors 'self';`, even without your config change.

**Comment by nowatbuer** [comment]
with the change I have made activating
Header set Content-Security-Policy "frame-ancestors 'self';"

so that it works, curl gives me the following:
HTTP/2 404 
alt-svc: h3=":443"; ma=2592000
cache-control: no-cache, no-store, must-revalidate
content-security-policy: frame-ancestors 'self';
content-type: text/html; charset=UTF-8
date: Fri, 13 Dec 2024 16:14:41 GMT
feature-policy: autoplay 'self';camera 'none';fullscreen 'self' http://cloud.xxx.de;geolocation 'self';microphone 'none';payment 'none'
referrer-policy: no-referrer
server: Apache/2.4.62 (Debian)
set-cookie: ocjz37u27r5q=d756b5c7b270741bc5f5d4e4bb9e421e; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: oc_sessionPassphrase=vPx92IVmIkaLrMJLv0pEhjZItBDqM7KU75X1WGAN9o299iKQxDECAqEeTKF7GC%2B17i7fN1o0JdDduC7IELlcnH0Rn%2F8e%2BXEK1%2F%2FGD3fV9HSFHS%2Bs%2FDel5l8FyI2kIhHj; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: ocjz37u27r5q=d756b5c7b270741bc5f5d4e4bb9e421e; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
set-cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
set-cookie: ocjz37u27r5q=d756b5c7b270741bc5f5d4e4bb9e421e; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: ocjz37u27r5q=d756b5c7b270741bc5f5d4e4bb9e421e; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: ocjz37u27r5q=2bf82e1082b6801404af15d606be8e96; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: cookie_test=test; expires=Fri, 13 Dec 2024 17:14:42 GMT; Max-Age=3600
strict-transport-security: max-age=15552000; includeSubDomains
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-powered-by: PHP/8.2.26
x-request-id: R2PUNsPtdVEfJROKJdEC
x-robots-tag: noindex, nofollow
x-xss-protection: 1; mode=block
content-length: 6640


with the not working original config I get:
HTTP/2 404 
alt-svc: h3=":443"; ma=2592000
cache-control: no-cache, no-store, must-revalidate
content-security-policy: default-src 'none';base-uri 'none';manifest-src 'self';script-src 'nonce-rb5OyjCS4njtJ4m6B1rKwdJu4F5uv8v3MbCBJB0Y6Tc=';script-src-elem 'strict-dynamic' 'nonce-rb5OyjCS4njtJ4m6B1rKwdJu4F5uv8v3MbCBJB0Y6Tc=';style-src 'self' 'unsafe-inline';img-src 'self' data: blob: https://*.tile.openstreetmap.org http://cloud.xx.de;font-src 'self' data:;connect-src 'self';media-src 'self';frame-src 'self' nc: http://cloud.xx.de;frame-ancestors 'self' http://cloud.xx.de;worker-src blob:;form-action 'self' http://cloud.xx.de
content-type: text/html; charset=UTF-8
date: Fri, 13 Dec 2024 16:17:32 GMT
feature-policy: autoplay 'self';camera 'none';fullscreen 'self' http://cloud.xx.de;geolocation 'self';microphone 'none';payment 'none'
referrer-policy: no-referrer
server: Apache/2.4.62 (Debian)
set-cookie: ocjz37u27r5q=683ad8745a4b982227ea969c1b407da2; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: oc_sessionPassphrase=RvvtH%2FcPZk3xIl1oWbDvxP%2BWZfKZ9y10NX1%2BwWeX2HvvyjQP9aCVHS5%2Bm5j0vSTPqVXIbiad59ZM5o6pzQkToxXvokuLmnUNUmZxW%2FfVk%2Fvd41a0gGSpiO2q5yo5%2BTKN; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: ocjz37u27r5q=683ad8745a4b982227ea969c1b407da2; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
set-cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
set-cookie: ocjz37u27r5q=683ad8745a4b982227ea969c1b407da2; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: ocjz37u27r5q=683ad8745a4b982227ea969c1b407da2; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: ocjz37u27r5q=1dca734b158b0fc052beb18f427a82d5; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: cookie_test=test; expires=Fri, 13 Dec 2024 17:17:33 GMT; Max-Age=3600
strict-transport-security: max-age=15552000; includeSubDomains
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-powered-by: PHP/8.2.26
x-request-id: FbiaeYMwFEcQOu9TyqpA
x-robots-tag: noindex, nofollow
x-xss-protection: 1; mode=block
content-length: 6640

Hope this helps

**Comment by joshtrichards** [comment]
```
content-security-policy: default-src 'none';base-uri 'none';manifest-src 'self';script-src 'nonce-rb5OyjCS4njtJ4m6B1rKwdJu4F5uv8v3MbCBJB0Y6Tc=';script-src-elem 'strict-dynamic' 'nonce-rb5OyjCS4njtJ4m6B1rKwdJu4F5uv8v3MbCBJB0Y6Tc=';style-src 'self' 'unsafe-inline';img-src 'self' data: blob: https://*.tile.openstreetmap.org http://cloud.xx.de;font-src/ 'self' data:;connect-src 'self';media-src 'self';frame-src 'self' nc: http://cloud.xx.de;frame-ancestors/ 'self' http://cloud.xx.de;worker-src/ blob:;form-action 'self' http://cloud.xx.de/
```

```
Failed to construct 'Worker': Access to the script at 'https://cloud.xx.de/apps/riotchat/riot/bundles/1c4a7dc1375053e9cf63/playback.worker.js' is denied by the document's Content Security Policy.
```

You'll note your CSP error is referencing an `https` URL but your CSP has `http` in it. I suspect your Nextcloud config and/or reverse proxy config (it can be a combination) isn't 100% right.
