### ISSUE TITLE
No connection to local synapse/matrix server

### ISSUE THREAD

**Issue by remi75** [gary-kim/riotchat#73]
Steps to reproduce

    Install / activate Riot Chat module
    Configure the server's url
    Try to use / connect Riot Chat module

Expected behaviour

A connection .
Actual behaviour

Doesn't connect . msg: connection impossible to localhost:8008
Server configuration

Operating system: debian 10

Web server: apache 2.4

Database: mariaDB 10

PHP version: php7.3

Nextcloud version: 19

Fresh installation

Where did you install Nextcloud from:
https://download.nextcloud.com/server/releases/nextcloud-19.0.0.tar.bz2

Are you using external storage, if yes which one: local/smb/sftp/... : No

Are you using encryption: Yes

**Are you using an external user-backend, No
Client configuration

Browser: Firefox 76.0.1

Operating system: Linux

On the server, launching : lynx http://localhost:8008 or lynx localhost:8008
gives a positive greeting message from the im server .

Also, I have sniffed the network layer with tcpdump, I saw zero trafic on port 8008 , while trying to connect thru nextcloud .

**Comment by gary-kim** [comment]
So, I'm assuming you already have a Matrix homeserver set up but it's on localhost? Is this a test instance where the Matrix homeserver and Nextcloud are both running on your system?

**Comment by remi75** [comment]
Hello,
Yes:

matrix-synapse/stable,stable,now 0.99.2-6 all [installed]
  Matrix reference homeserver

python3    1637 matrix-synapse   11u  IPv6   26047      0t0  TCP localhost:8008 (LISTEN)
python3    1637 matrix-synapse   12u  IPv4   26048      0t0  TCP localhost:8008 (LISTEN)

On a debian 10 
python3.7/stable,now 3.7.3-2+deb10u1
php7.3/stable,stable,now 7.3.14-1~deb10u1

Thank you

**Comment by gary-kim** [comment]
Just to confirm, does it work with a different homeserver?
Also, can you connect to localhost using a different Riot instance? <https://riot.im/app> would be a good way to test that.

**Comment by remi75** [comment]
yes it does without a glitch

**Comment by remi75** [comment]
ok i'll do that and tell you

**Comment by remi75** [comment]
connection from:  

https://riot.im/app    ok

lynx http://185.246.87.186:8008      from localhost ok
lynx http://185.246.87.186:8008      from client pc  ok
firefox http://185.246.87.186:8008  from  client pc ok

from within nextclout/riotchat http://185.246.87.186:8008  says connection impossible.

and tcpdump still shows zero packets on port 8008 .

I suspect the app that it assumes/tries a secure(ssl) version , but you'r the one who'd know :)


Thank you again for the help

**Comment by gary-kim** [comment]
Yeah, it's likely that Nextcloud's security policy is preventing non-https connections.

**Comment by remi75** [comment]
It could be understood, but it makes no sense to activate SSL on the local IP: 127.0.0.1
I mean it is like using ssh localhost, instead of launching another instance of bash on your terminal :)
And I had opened a ticket with NC, but they rejected it saying it is related to Riotchat, not NC ...
Is there any advice I can get to tweak NC ?
Or will you look into it on your side ?

Regards

**Comment by gary-kim** [comment]
I'd say that accessing a localhost non-ssl Matrix homeserver is an unsupported setup. Sorry about that.

**Comment by remi75** [comment]
Well, it is pity, because synapse/matrix has SSL, logically as an option, and is supported like that, just like apache, you have http, and for SSL, it is up to you to activate it and get a certificate ... :)
and,   **https://riot.im/app**  was able to connect to my non-SSL instance ...
So here I'd prefer if we say,

This _riotchat_ does not support non SSL activated matrix servers; even on localhost .

And that gets me to the point of thinking:

You don't want to look into it, or you cant ?

Because adding SSL in a program it is actually extra work .

If it is you that has done it, you know which lines have to be commented out ... ;
yes I program too, but very busy these days, so I'll do it my self later on ...

Or you have just copied and pasted code without understanding it, hence you are stuck here .

I also inform you that SSL is extra work for the CPU, for very frequented servers on low end machines, it does matter . 

Gutt Nuecht

**Comment by gary-kim** [comment]
I say that it is an unsupported setup because, as the Synapse install instructions say regarding http: 
>  It is suitable for local testing, but for any practical use, you will need Synapse's APIs to be served over HTTPS.

See [here](https://github.com/matrix-org/synapse/blob/master/INSTALL.md#tls-certificates).

This makes sense. Things like passwords and the messages themselves are going through that connection so using an unencrypted connection for that is very dangerous.

Now if you really want it to work over http for some reason, it's your browser that is blocking the connection. For Firefox, follow this [guide](https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox). You should get the mixed content warning after you try to put in your homeserver and it fails. You can also look up how to do it for Chromium based browsers.

https://riot.im/app doesn't seem to work for non-ssl homeservers for me either by default so I'm not sure why it worked for you, but that's an issue for another time.

**Comment by remi75** [comment]
Well, suitable and required, is not the same thing, so it functions without ssl .
And it is for local using after testing .
No it doesnt make sense in localhost, I remind you that localhost is 127.0.0.1, by design nothing outside the server can see it.
And as I said: the environment is already secured by https://nextcloud.host.tld

You think It is fun to configure 2 certificates for the same service ?

I don't want to federate.

No it is not firefox blocking, otherwise it would have warned me .
and the guide you showed makes it clear that you have no clue about what I am talking about .

It is also clear to me that you just copy and paste things thinking that an email with a .dev extension will impress people .

Sayonara
