### ISSUE TITLE
Project Name Change to "Element for Nextcloud"

### ISSUE THREAD

**Issue by gary-kim** [gary-kim/riotchat#97]
The project is being renamed to "Element for Nextcloud". We need to change all the instances of the old name being used while keeping the project ID, PHP namespace, and URLs the same.

We also need to update the disclaimer regarding being unrelated to the upstream project to reflect the new name.

https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$9r9cDRH7mRIvafglZGTCJRjnJx7kNqf3X8rj2iu3Dq8?via=matrix.org&via=privacytools.io&via=mozilla.org

Related to #79

**Comment by compgeniuses** [comment]
I can see quite a number of things will need to happen to effect a name change. to the developers, I understand the pain of effecting a name change in project without breaking things significantly.

From your end, are there any major UI changes with the new product now element?

**Comment by gary-kim** [comment]
Someone just needs to make a PR to change any mentions of Riot in the interface to be Element. The plan is not to change any of the code mentions for now so the app will still be called `RiotChat` in the code.

**Comment by gary-kim** [comment]
Listing the places in which the names have to be changed:

https://github.com/gary-kim/riotchat/blob/a57c815714c3f00618ecd695c4840585f073d361/lib/Settings/AdminSection.php#L72-L74

Multiple mentions of the name in: https://github.com/gary-kim/riotchat/blob/master/src/components/AdminSettings.vue

Also in the README: https://github.com/gary-kim/riotchat/blob/master/README.md

https://github.com/gary-kim/riotchat/blob/a57c815714c3f00618ecd695c4840585f073d361/appinfo/info.xml#L5-L15
